hoodie/icalendar

- src/calendar.rs
- src/components.rs
- src/lib.rs
- src/properties.rs
Running example/write.rs also now passes the iCalendar validator. https://icalendar.org/validator.html
> Comply to RFC Section 3.1 (content lines)

- examples/write.rs
- src/components.rs
Now we can set the UID property like the summary, location... but if we
dont set, the lib still generate a new
> Uid property

- src/calendar.rs
Please see individual commits.
> Various fixes for library usability by clients

- src/components.rs
- tests/calendar.rs
> Make Component serialization deterministic, add integration tests

- CHANGELOG.md
- Cargo.toml
- src/calendar.rs
- src/components.rs
- src/lib.rs
Implement basic [iCalendar venue draft](https://tools.ietf.org/html/draft-norris-ical-venue-01) properties
> Add iCalendar Venue Draft Support

- src/calendar.rs
Adds the following properties:
- name
- description
- timezone
- ttl
> Support calendar properties

- src/components/date_time.rs
- src/properties.rs
These will make testing easier.
> Derive some more traits.

- src/components.rs
- src/components/event.rs
- src/components/todo.rs
This adds a getter and setter for the URL property.
> Add support for URL property

- src/parser/components.rs
This is a pretty common pattern to extract a single prop from a component.
> Add Component::find_prop helper

- src/calendar.rs
- src/calendar/calendar_component.rs
- src/components.rs
- src/components/alarm.rs
- src/components/event.rs
- src/components/other.rs
- src/components/todo.rs
- src/components/venue.rs
- src/parser/properties.rs
- src/properties.rs
This just adds Clone derives to components.
It's a simple change which I needed myself for a project but I think that this would be a great addition to be featured in the official version
> Make components Clone

- src/parser/components.rs
- src/parser/parameters.rs
- src/parser/properties.rs
- src/parser/utils.rs
seems like nom will deprecate the combinator
> refactor: use Parser::map instead of combinator

- src/properties.rs
> feat: parameter from tuple

- Cargo.toml
- src/parser/components.rs
- src/parser/mod.rs
- src/parser/parameters.rs
- src/parser/parsed_string.rs
- src/parser/properties.rs
- src/parser/utils.rs
> update to nom 8

- Cargo.toml
- src/components/date_time.rs
> feat: add From-implementations for the time crate

- .github/workflows/ci.yml
- .github/workflows/pull-request.yml
> ci: allow convco to bypass semver-checks

- src/components.rs
> fix: serialize LAST-MODIFIED correctly

- .github/workflows/ci.yml
This reverts commit c0ffee3f32f36d4e55e127139300acdb612bd176.
<!--
```
```
->>
If you have any questions …
> ci: run push ci on PR again

- src/components.rs
<!--
```
```
->>
This is necessary to properly handle recurring events with changes to some recurrences.
> Add methods to get and set RECURRENCE-ID.

- README.md
> docs: add contributors section

- Cargo.toml
- README.md
- examples/change_status.rs
- src/calendar.rs
- src/components/event.rs
- src/components/todo.rs
- src/components/venue.rs
- tests/todo_uid_preservation.rs
> feat: allow marking complete todos as complete

- src/parser/utils.rs
Previously "begin", all lowercase, was interpreted as a valid property key, but only when parsing as a component failed. This meant that in the failure case, where there were many unclosed and lowercase `begin`s, the parse time would increase at an O(2^N) rate, taking ~8s for 20 unclosed `begin`s.
With the new and improved `property_key()`, it should be case-insensitive and work for arbitrary properties that begin with `begin` or `end`, which would not before.
Fixes: #155
> fix: resolve exponential parse time on unclosed components
