hoodie/icalendar

- Cargo.toml
- examples/tasks.rs
- src/components.rs
- src/lib.rs
- tests/calendar.rs
This introduces proper time zone and "floating" date-time handling for
Component::start() and Component::end(), by following means:
- we introduce new thin enum wrapper CalendarDateTime, which is either floating
(as per RFC) or in UTC (extendable in future for timezone-referenced date-time).
- we make Component::start(), Component::end() accept our CalendarDateTime instead
of `chrono::DateTime<TZ>` (more precisely we accept `T: Into<CalendarDateTime>`).
- we implement `From<chrono:DateTime<TZ>>` for CalendarDateTime, restoring source
compatibility with previous versions (but not interpretation compatibility),
and providing caller convenience. The implementation converts passed
date-time to Utc.
- we also implement `From<chrono:NaiveDateTime>` for CalendarDateTime, which
converts to …
> Time zone handling: convert DateTime to UTC, NaiveDateTime to floating reference

- src/calendar.rs
As pointed out already in #11 (ref [std::string::ToString](https://doc.rust-lang.org/stable/std/string/trait.ToString.html)) implementing `ToString` directly isn't such a great idea, especially since it may panic. Hence this replaces our `ToString` impl with a `Display` impl.
> fix: remove ToString and implement fmt::Display instead

- src/calendar.rs
- src/components.rs
- src/components/date_time.rs
- src/components/event.rs
- src/components/todo.rs
- src/components/venue.rs
- src/properties.rs
Being able to parse an iCalendar file into a `Calendar` isn't much use if you can't then access the data in it in a useful way.
This PR adds typed getters to `Calendar`, `Event`, `Todo`, `Venue` and the `Component` trait, to get the same properties as the builder methods allow to be set.
I also:
* Derived some more basic traits (`Clone`, `PartialEq`, `Eq`) on some of the types that were missing them (`Parameter`, `Property`, `Class`, `ValueType`, `EventStatus`, `TodoStatus`).
* Added a getter on `Property` for the `ValueType`, and for the map of parameters.
* Allow a due date (without a time) to be specified for a `TODO`, as allowed by the RFC.
> Add getters for calendar and event properties

- README.md
- src/components/date_time.rs
- src/lib.rs
#37 added the new type `DatePerhapsTime`, but I forgot to make a public export of it, so the new methods returning it couldn't actually be used. This PR fixes that, and also fixes a typo in the readme.
> Fix typo in readme and missing export

- README.md
- examples/readme.rs
- src/components.rs
- src/components/date_time.rs
- src/components/todo.rs
- src/lib.rs
- src/parser/components.rs
- src/properties.rs
- tests/try_into_string.rs
This fixes some issues and adds some new functionality. In particular:
* `start_date` and `end_date` were taking a date with a timezone, but then ignoring the timezone. I've removed them, and instead changed `starts` and `ends` to take `impl Into<DatePerhapsTime>`, which includes the `NaiveDate` case.
* Similarly, I've changed `all_day` to take a `NaiveDate` rather than a date with a timezone which is then ignored.
* According to RFC5545, DTSTAMP must be in UTC, but the `timestamp` method was accepting a `impl Into<CalendarDateTime>`. I've fixed this to only allow `DateTime<Utc>` to match the spec, and similarly fixed the getter to return the same.
* I've added support for setting and getting date-time values with a TZID. For now the TZID is just a string, so the client needs to handle …
> Clean up date/time handling and add support for date-times with a TZID

- src/parser/mod.rs
- src/parser/parsed_string.rs
This small change ensures `ParseString` is included in the generated docs,
which is mostly useful for newcomers like myself.
> Publish docs for ParseString

- src/components/date_time.rs
- src/parser/calendar.rs
- src/parser/components.rs
This adds a helper `TryFrom` implementation to convert parsed properties
into DatePerhapsTime.
Fixes: https://github.com/hoodie/icalendar-rs/issues/44
> Convert parsed properties into DatePerhapsTime

- src/calendar.rs
This allows accessing events from a calendar that has been parsed from a ICS file. Use cases include for instance deleting exiting events from a calendar.
> Make Calendar components and properties public

- Cargo.toml
on main:
```
Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.44
└── chrono 0.4.22
└── icalendar 0.13.1
error: 1 vulnerability found!
```
This removes the oldtime feature of chrono and fixes `cargo audit`
> fix: disable oldtime feature of chrono

- Cargo.toml
The `pretty_assertions` crate is both a dev and a non-dev dependency. At the same time, it's only actually ever used in test code. Hence, remove the non-dev dependency, as it is unused anyway.
> Remove pretty_assertions dependency

- src/calendar.rs
There does not seem to be a good reason for making the `Calendar::property_value()` method private: the accessed property array is public anyway and it is nothing more than a helper. What's more, calendar components have exactly a method of this name (fulfilling a similar purpose) publicly available.
Declare it as public to make it accessible to users, instead of forcing them to copy and paste it.
> feat: Make Calendar::property_value() publicly accessible

- Cargo.toml
The `uuid` crate needs the feature `js` to support compiling for wasm.
> Wasm support

- src/parser/mod.rs
Went looking for read_calendar_verbose() when I saw this comment. Seems like the update was missed in 519c4851a34daed31e109348f96acad18408eeda
> docs: update references to renamed parser functions

- src/components.rs
- src/components/other.rs
- src/parser/components.rs
- src/parser/properties.rs
WIP: Add support for multi-properties in calendar parsing.
- Updated InnerComponent multi_property from Vec<Property> to BTreeMap<String, Vec<Property>>
- When converting into InnerComponent, split the properties by those that "May occur more than once" and all others
- Added a basic test as proof of concept
- Still to do is add filtering for other properties such as attach, cattegory, etc.
> fix: support for multi-properties

- README.md
- src/lib.rs
- src/parser/mod.rs
- src/parser/utils.rs
- src/properties.rs
> fix: forbid index slicing in parser

- examples/custom_property_parsed.rs
- examples/full_circle.rs
- src/parser/parsed_string.rs
- src/parser/properties.rs
- src/properties.rs
- tests/full_circle.rs
- tests/reserialize.rs
thanks to @luca-iachini for noticing that the escapign of text is not implemented correctly. this should address this.
still considering making this a breaking change since the output of the serializer is no longer compatible with that of previous versions
> fix escaping

- src/components.rs
- src/components/alarm.rs
- src/components/date_time.rs
- src/lib.rs
- src/parser/parsed_string.rs
- src/parser/properties.rs
- src/properties.rs
- src/value_types.rs
We now look determine the value-type of a property (either by name or parameter) and escape/unescape accordingly.
This fixes #104 
At the moment this only distinguishes between `TEXT` and non-`TEXT`, but technically the value type should also be considered when parsing dates vs durations etc.
> fix: escape according to value types

- src/properties.rs
- tests/reserialize.rs
Thanks for this crates, it is really ergonomic to use, but I found a little uncommon bug:
In the section 3.1 of RFC 5545, the line size limit is stated to be no more than 75 bytes excluding the linebreak. This does not exclude the space character from the 75 bytes limit, so it needs to be taken into account in the folding algorithm. This PR fixes this bug and the corresponding test that assert the 76 bytes line.
> fix: wrapping behaviour does no take added space into account

- .github/pull_request_template.md
- .github/workflows/ci.yml
- src/components.rs
- src/components/alarm.rs
- src/components/date_time.rs
- src/components/todo.rs
- src/properties.rs
- tests/reserialize.rs
Another little PR, but it is only to make the user interface a bit nicer to work with.
It allows to use the same function for owned String and slices. By using `impl Into<String>`, it convert string slices to String when it receives a string slices, but when a String is passed, it will just move it. The implementation of Into<T> for the same type is a function that just return the same type, so it's a zero cost operation. [https://doc.rust-lang.org/src/core/convert/mod.rs.html#763-771](https://doc.rust-lang.org/src/core/convert/mod.rs.html#763-771)
I marked the old method deprecated, so at the next major release with breaking changes, they could be removed.
> refactor: standardizes Property::new and Property::new_pre_alloc methods with generics

- src/properties.rs
As outlined in #111, COLONs should not be escaped with a BACKSLASH in a TEXT property (capitalization to match the spec).
This removes the line I found that was doing it, a quick test run generated a valid ical file based on my usecase (as validated via https://icalendar.org/validator.html)
All tests still pass. I'm however unfamiliar with the code base and my usecase is limited in complexity, so please double check me
> fix: remove colon escape in text property

- src/components.rs
> feat: add `LAST_MODIFIED` and `CREATED` getters and setters

- src/components/date_time.rs
Refs: #118
<!--
```
```
->>
If you have any questions or need assistance, don't hesitate to ask. We're …
> feat: add type conversion DatePerhapsTime <-> NaiveDate

- src/calendar.rs
As the commit and PR title say, these changes add a small convenience method to the `Calendar` struct for parsing the `REFRESH-INTERVAL` or `X-PUBLISHED-TTL` calendar property value back into a chrono `TimeDelta`. This is useful for iCalendar web clients to decide how often then should poll for calendar updates, for example.
> feat: add `get_ttl` counterpart method to `Calendar`

- src/components/date_time.rs
This PR exposes the aforementioned methods as part of the public API. These methods are valuable for downstream consumers who need to interpret properties that may hold date or datetime values, as defined by the iCalendar standard and beyond. There doesn't appear to be a compelling reason to keep these methods private, as their usefulness extends beyond internal implementation details and they cannot be misused to violate invariants.
For example, I found these methods particularly helpful for safely extracting `RECURRENCE-ID`, `RDATE`s, and `EXDATE` values to pass along to the [`rrule`](https://crates.io/crates/rrule) crate to expand recurring `VEVENT`s.
> feat: expose `DatePerhapsTime` property roundtrip methods as public API

- src/properties.rs
Although the iCalendar specification allows either, some software doesn't support \N.
See #87 for context.
> Use \n rather than \N for encoding newlines.

- src/components.rs
BREAKING CHANGE: 
Sets/Reads the property `LAST-MODIFIED` instead of `LAST_MODIFIED` in the corresponding functions in order to adhere to the RFC 5545 standard. 
This will break programs which are using this property, write the result to a file, parse the file and then access the property again using these functions.
> fix: use 'LAST-MODIFIED' instead of 'LAST_MODIFIED' property

- README.md
This PR removes the `done` calls from the README examples, which were missed in the previous PR.
BTW, I noticed that `done` is still used in many places throughout the codebase. Should we consider cleaning them up, or even marking `done` as deprecated?
Follow up: #148
<!-- …
> docs: remove done

- src/components.rs
- src/components/todo.rs
- src/components/venue.rs
This PR adds multiple `remove_xxx` methods for properties that have corresponding `xxx()` setters or `get_xxx()` getters (excluding `uid`, which is required), along with related tests.
Also, thanks for the great work!
Follow up: #141
<!--
```
feat: add new user authentication …
```
> feat: add remove_xxx method for optional propeties

- src/components/alarm.rs
- src/properties.rs
This is just like issue #7, and I applied the same fix.
I also replaced `HashMap::new()` with `Default::default()` which I think does the same thing but doesn't require you to name the type, so it's more future-proof.
`cargo test` and `cargo clippy` passed locally. This crate has been instrumental for my calendar project, so thank you for maintaining it!
> fix: use BTreeMap in properties, so they'll be serialized deterministically
